
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package TrabajoFinal.AnalizadorLexSinSem;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 7;
  public static final int Parentesis_c = 18;
  public static final int For = 9;
  public static final int Parentesis_a = 17;
  public static final int Suma = 13;
  public static final int Numero = 23;
  public static final int Var = 3;
  public static final int ERROR = 24;
  public static final int Function = 10;
  public static final int Identificador = 22;
  public static final int Llave_c = 20;
  public static final int Const = 4;
  public static final int Llave_a = 19;
  public static final int P_coma = 21;
  public static final int EOF = 0;
  public static final int Division = 16;
  public static final int Resta = 14;
  public static final int If = 6;
  public static final int Linea = 2;
  public static final int Return = 11;
  public static final int error = 1;
  public static final int Igual = 12;
  public static final int While = 8;
  public static final int Multiplicacion = 15;
  public static final int Let = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Linea",
  "Var",
  "Const",
  "Let",
  "If",
  "Else",
  "While",
  "For",
  "Function",
  "Return",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "P_coma",
  "Identificador",
  "Numero",
  "ERROR"
  };
}

